extends Resource
## Art-only settings. No damage, collision, status or gameplay timing is owned here.
@export var spire_meshes: Array[Mesh]
@export var chip_mesh: Mesh
@export var spire_material: ShaderMaterial
@export var chip_material: Material
@export var ground_material: ShaderMaterial
@export var ring_material: ShaderMaterial
@export var mist_material: ShaderMaterial
@export var spark_material: Material
@export var rise_curve: Curve
@export var vanish_curve: Curve
@export var chip_scale_curve: Curve
@export var visual_seed: int
@export var duration_sec: float
@export var anticipation_sec: float
@export var travel_sec: float
@export var rise_sec: float
@export var hold_sec: float
@export var sink_sec: float
@export var length_m: float
@export var station_count: int
@export var height_range: Vector2
@export var width_range: Vector2
@export var lateral_spread: float
@export var satellite_scale: Vector2
@export var lean_deg: Vector2
@export var crown_count: int
@export var crown_radius: float
@export var crown_height_scale: Vector2
@export var crown_width_scale: float
@export var crown_stagger_sec: float
@export var crown_chip_count: int
@export var crown_spark_count: int
@export var crown_burst_speed_scale: float
@export var ground_width: float
@export var ground_height: float
@export var ring_radius: float
@export var ring_duration: float
@export var chip_count: int
@export var chip_size: Vector2
@export var chip_speed: Vector2
@export var chip_up_speed: Vector2
@export var chip_gravity: float
@export var chip_lifetime: Vector2
@export var chip_bounce: float
@export var chip_drag: float
@export var mist_count: int
@export var mist_size: Vector2
@export var mist_lifetime: Vector2
@export var mist_spread: float
@export var mist_rise: float
@export var spark_count: int
@export var spark_size: Vector2
@export var spark_speed: Vector2
@export var spark_lifetime: Vector2
@export var spark_gravity: float
@export var light_color: Color
@export var light_energy: float
@export var light_radius: float
@export var light_height: float
@export var light_pulse_sec: float
