extends Resource
## Presentation-only settings for the isolated eruption gallery.

@export var effects: Array[PackedScene]
@export var effect_keys: PackedStringArray
@export var theme: Theme
@export var font: Font
@export var translations: Array[Translation]
@export var initial_locale: String
@export var floor_material: Material
@export var camera_position: Vector3
@export var camera_target: Vector3
@export var camera_fov: float
@export var floor_size: Vector2
@export var floor_center: Vector3
@export var platform_size: Vector3
@export var platform_position: Vector3
@export var stone_color: Color
@export var metal_color: Color
@export var edge_color: Color
@export var ice_color: Color
@export var rock_color: Color
@export var edge_energy: float
@export var pillar_positions: PackedVector3Array
@export var pillar_size: Vector3
@export var pillar_cap_size: Vector3
@export var pillar_band_size: Vector3
@export var pillar_light_height: float
@export var pillar_light_range: float
@export var pillar_light_energy: float
@export var key_position: Vector3
@export var key_color: Color
@export var key_energy: float
@export var key_size: float
@export var fill_position: Vector3
@export var fill_color: Color
@export var fill_energy: float
@export var fill_size: float
@export var ambient_color: Color
@export var ambient_energy: float
@export var background_color: Color
@export var glow_intensity: float
@export var fog_density: float
@export var fog_color: Color
@export var loop_interval: float
@export var slow_speed: float
@export var capture_fps: int
@export var capture_frames: int
@export var capture_resolution: Vector2i
@export var ui_margin: int
@export var title_size: int
@export var subtitle_size: int
@export var control_size: int
@export var info_size: int
@export var text_color: Color
@export var muted_color: Color
@export var panel_color: Color
@export var button_min_size: Vector2
@export var stage_line_width: float
@export var stage_line_length: float
@export var stage_line_positions: PackedVector3Array
@export var details: Dictionary
