extends Resource
## Presentation-only values. Combat owns projectile position, radius and contacts.
@export var blade_mesh: Mesh
@export var shard_mesh: Mesh
@export var blade_material: ShaderMaterial
@export var halo_material: ShaderMaterial
@export var ribbon_material: ShaderMaterial
@export var shard_material: Material
@export var mist_material: ShaderMaterial
@export var ring_material: ShaderMaterial
@export var flash_material: ShaderMaterial
@export var blade_scale: Vector3
@export var blade_tilt_deg: float
@export var projectile_unit_scale: Vector3
@export var halo_scale: Vector3
@export var embedded_shard_count: int
@export var embedded_shard_size: Vector2
@export var echo_offsets: PackedVector3Array
@export var echo_scales: PackedVector3Array
@export var echo_opacity: PackedFloat32Array
@export var ribbon_count: int
@export var ribbon_segments: int
@export var ribbon_length: float
@export var ribbon_width: float
@export var ribbon_spread: float
@export var ribbon_wave: float
@export var visual_seed: int
@export var trail_count: int
@export var trail_lifetime: Vector2
@export var trail_size: Vector2
@export var trail_spread: float
@export var trail_speed: float
@export var trail_gravity: float
@export var mist_count: int
@export var mist_size: Vector2
@export var mist_opacity: float
@export var light_color: Color
@export var light_energy: float
@export var light_range: float
@export var burst_count: int
@export var burst_size: Vector2
@export var burst_speed: Vector2
@export var burst_gravity: float
@export var burst_duration: float
@export var burst_mist_count: int
@export var burst_mist_size: Vector2
@export var burst_mist_spread: float
@export var impact_ring_radius: float
@export var impact_flash_size: float
@export var impact_flash_duration: float
@export var charge_sec: float
@export var flight_sec: float
@export var flight_distance: float
@export var flight_height: float
@export var duration_sec: float
@export var trail_exit_sec: float
@export var growth_curve: Curve
@export var fade_curve: Curve
