extends Resource
@export var toggle_event: InputEventKey
@export var background: Color
@export var paper: Color
@export var ink: Color
@export var muted: Color
@export var accent: Color
@export var line_color: Color
@export var node_colors: Dictionary[String, Color]
@export var icons: Dictionary[String, Texture2D]
@export var margin: int
@export var gap: int
@export var sidebar_width: float
@export var column_pitch: float
@export var row_pitch: float
@export var canvas_padding: float
@export var node_radius: float
@export var icon_size: float
@export var line_width: float
@export var title_size: int
@export var body_size: int
@export var small_size: int
@export var node_font_size: int
@export var button_height: float
@export var layout_passes: int
@export var layout_backoff_steps: int
@export var neighbour_pull: float
@export var row_sway: float
@export var sway_frequency: float
@export var node_jitter: Vector2
@export var max_shift_x: float
@export var label_spacing: Vector2
@export var minimum_edge_rise: float
@export var path_clearance: float
@export var curve_bend: float
@export var curve_segments: int
@export var path_dash_length: float
@export var path_dash_gap: float
@export var marker_inset: float
@export var marker_radius: float
