extends "res://tests/enemy_roles.gd"
const BuildLoader = preload("res://content/builds/build_loader.gd")
const Statuses = preload("res://combat/status/status_runtime.gd")
const BuildFixture = preload("res://tests/fixtures/action_build_fixture.gd")
const BuildRuntime = preload("res://combat/builds/build_runtime.gd")
const Caps = preload("res://combat/builds/projectile_capabilities.gd")
var builds
var statuses := Statuses.new()
var source := {"source_handle":1,"team":0,"root_id":1,"room_generation":1,"ability_id":"test"}
func run() -> void:
	combat = CombatLoader.new().load_catalog()
	enemies = EnemyLoader.new().load_catalog(combat)
	builds = BuildLoader.new().load_catalog()
	statuses.configure(builds)
	world = Node3D.new()
	root.add_child(world)
	check_status_lifecycle()
	check_responses()
	check_merge_and_invalid()
	check_all_brains()
	check_flying_arrow()
	check_candidates_and_snapshot()
	statuses.clear()
	world.free()
	print("STATUS_CONTROLS ", JSON.stringify({"failures": failures}))
	quit(0 if failures.is_empty() else 1)
func check_status_lifecycle() -> void:
	var a = actor("brute", Vector3.ZERO)
	var slow: Dictionary = builds.status("test_slow")
	var freeze: Dictionary = builds.status("test_freeze")
	check(statuses.apply(a,slow.id,slow.duration_sec,source), "apply slow")
	check(is_equal_approx(a.control_move_scale,slow.move_scale), "slow is derived multiplier")
	statuses.tick(0.5)
	var before := statuses.snapshot(a)
	statuses.tick(0.0)
	check(before == statuses.snapshot(a), "pause freezes status clock")
	statuses.apply(a,slow.id,0.2,source)
	check(statuses.snapshot(a) == before, "shorter reapply cannot shorten or stack")
	statuses.apply(a,slow.id,slow.duration_sec,source)
	check(statuses.snapshot(a)[slow.id].remaining == slow.duration_sec, "refresh replaces remaining; does not add")
	a.enemy_move_multiplier = 1.3
	a.movement = Vector3.RIGHT
	a.step(0.016)
	check(is_equal_approx(a.velocity.length(),a.definition.speed * 1.3 * slow.move_scale), "motor combines current aura and slow once")
	a.runner.start(a.attacks[0], Vector3.FORWARD)
	statuses.apply(a,freeze.id,freeze.duration_sec,source)
	check(a.control_locked and not a.runner.busy() and not a.runner.active_this_step, "freeze cancels uninterruptible heavy attack")
	check(not statuses.apply(a,freeze.id,freeze.max_duration_sec,source), "active freeze cannot be refreshed by a longer application")
	check(not a.runner.start(a.attacks[0], Vector3.FORWARD), "executor denies new casts while frozen")
	a.motor.knockback(Vector3.RIGHT,10.0,1.0)
	a.motor.step(Vector3.RIGHT,10.0,0.1,false)
	check(a.velocity == Vector3.ZERO and a.motor.impulse_left == 0.0, "frozen motor rejects forced/knockback movement")
	statuses.tick(freeze.duration_sec)
	check(not a.control_locked and a.control_move_scale == slow.move_scale and not a.runner.busy(), "thaw recomputes remaining slow without resuming canceled cast")
	statuses.remove(a,slow.id)
	check(a.control_move_scale == 1.0 and a.enemy_move_multiplier == 1.3, "remove does not overwrite aura/base stats")
	check(not statuses.apply(a,freeze.id,freeze.duration_sec,source), "thaw immunity remains after last active status is removed")
	statuses.tick(builds.control_group(freeze.control_group).thaw_immunity_sec)
	check(statuses.apply(a,freeze.id,freeze.duration_sec,source), "freeze can apply again after thaw immunity expires")
	a.receive_hit(a.health.maximum)
	check(statuses.snapshot(a).is_empty() and not a.runner.actions_allowed, "death clears instances and cannot reenable actions")
	statuses.tick(10.0)
	check(not a.health.alive() and not a.runner.busy(), "expiry cannot resurrect actions")
	a.free()
func check_responses() -> void:
	var data: Dictionary = JSON.parse_string(FileAccess.get_file_as_string("res://data/builds/prototype.json"))
	data.status_rules.actor_responses = {"brute":"immune", "scout":"resistant"}
	var manager := Statuses.new()
	manager.configure(BuildLoader.new().decode(data))
	var a = actor("brute", Vector3.ZERO)
	var b = actor("scout", Vector3.ZERO)
	check(not manager.apply(a,"test_freeze",1.0,source) and not manager.apply(a,"test_slow",1.0,source), "explicit immunity rejects target independent of source compatibility")
	manager.apply(b,"test_freeze",1.0,source)
	check(is_equal_approx(manager.snapshot(b).test_freeze.remaining,0.5), "resistance scales duration")
	manager.clear()
	check(not b.control_locked and manager.visuals().is_empty(), "room clear removes all control")
	data.statuses[0].move_scale = 0.0
	check(BuildLoader.new().decode(data) == null, "slow cannot masquerade as freeze")
	a.free(); b.free()
func check_all_brains() -> void:
	for id in ["scout","brute","crossbow","charger","banner"]:
		var player = actor("player",Vector3.ZERO)
		var enemy = actor(id,Vector3(0,0,-6) if id in ["crossbow","charger","banner"] else Vector3(0,0,-1))
		var r = runtime(player)
		var brain = add(r,enemy)
		brain.tick(0.01)
		if id in ["scout","brute"]: enemy.step(0.01)
		if id == "charger": brain.tick(brain.time_left)
		statuses.apply(enemy,"test_freeze",1.0,source)
		var old_position: Vector3 = enemy.position
		var hp: float = player.health.current
		for step in 5:
			brain.tick(0.2)
			enemy.step(0.2)
			r.after_motion(0.2)
		check(enemy.position == old_position and enemy.forced_velocity == Vector3.ZERO, id + " immobilized through actual decision/motor path")
		check(r.projectiles.is_empty() and player.health.current == hp, id + " cannot emit stale shot/charge damage")
		check(brain.state == "frozen", id + " reports frozen state")
		statuses.clear()
		check(not enemy.runner.busy(), id + " old attack stays canceled after control removal")
		r.clear()
		player.free(); enemy.free()
	var player = actor("player",Vector3(0,0,6))
	var banner = actor("banner",Vector3.ZERO)
	var brute = actor("brute",Vector3(1,0,0))
	var r = runtime(player)
	add(r,banner); add(r,brute)
	r.update_auras()
	check(brute.aura_active, "banner aura initially active")
	statuses.apply(banner,"test_freeze",1.0,source)
	r.update_auras()
	check(not brute.aura_active and brute.enemy_attack_multiplier == 1.0, "frozen banner cannot emit aura")
	statuses.tick(1.0)
	r.update_auras()
	check(brute.aura_active, "aura recomputes after thaw")
	r.clear(); player.free(); banner.free(); brute.free()
func check_flying_arrow() -> void:
	var player = actor("player",Vector3.ZERO)
	var bow = actor("crossbow",Vector3(0,0,-6))
	var r = runtime(player)
	var brain = add(r,bow)
	brain.tick(0.01)
	brain.tick(brain.time_left)
	check(r.projectiles.size() == 1, "crossbow fires before freeze")
	var before: Vector3 = r.projectiles[0].position
	statuses.apply(bow,"test_freeze",1.0,source)
	r.after_motion(0.1)
	check(r.projectiles.size() == 1 and r.projectiles[0].position != before, "existing enemy projectile continues after source freeze")
	statuses.clear();r.clear();player.free();bow.free()
func check_candidates_and_snapshot() -> void:
	# Bound offer/transaction loops are covered by bound_build_session. This gate
	# retains carrier-scoped status qualification and live in-flight snapshots.
	var upgrade: Dictionary = builds.upgrade("freeze_duration")
	var empty: Dictionary = BuildFixture.compile(builds, {}, "primary")
	var primary: Dictionary = BuildFixture.compile(builds, {"contact_freeze":1}, "primary")
	check(not Caps.eligible(upgrade,Caps.summarize_plan(builds,empty.actions.primary)), "duration boost unavailable without own freeze source")
	check(Caps.eligible(upgrade,Caps.summarize_plan(builds,primary.actions.primary)), "same-action freeze unlocks duration without active frozen target")
	check(not Caps.eligible(upgrade,Caps.summarize_plan(builds,primary.actions.special)), "other action cannot supply freeze modifier requirement")
	check(Caps.eligible(builds.upgrade("contact_freeze"),Caps.summarize_plan(builds,empty.actions.primary)), "freeze core has no circular self prerequisite")
	var player = actor("player",Vector3.ZERO)
	var target = actor("brute",Vector3(0,0,-1))
	var build := BuildRuntime.new()
	build.configure(builds,player,func():return [target],Callable(),["test_arrow"])
	check(build.set_program(BuildFixture.compile(builds,{"contact_freeze":1},"debug_arrow")), "explicit debug-arrow freeze fixture compiles")
	build.statuses.apply(player,"test_freeze",1.0,source)
	check(not build.fire_attack("test_arrow",Vector3.FORWARD), "frozen source cannot bypass action gate with test arrow")
	player.request_dodge()
	check(not player._dodge_requested, "frozen source cannot buffer a dodge for thaw")
	build.statuses.remove(player,"test_freeze")
	check(build.fire_attack("test_arrow",Vector3.FORWARD), "thawed source can fire debug fixture")
	check(build.set_program(BuildFixture.compile(builds,{"contact_freeze":1,"freeze_duration":1},"debug_arrow",2)), "later debug fixture extends future casts only")
	build.tick(0.001);build.tick(0.1)
	var target_status := build.statuses.snapshot(target)
	check(target_status.has("test_freeze"), "in-flight debug arrow carries its own freeze")
	if target_status.has("test_freeze"):
		check(is_equal_approx(target_status.test_freeze.remaining,builds.status("test_freeze").duration_sec), "in-flight status duration uses fire snapshot")
	build.clear_room()
	check(not target.control_locked and build.statuses.snapshot(target).is_empty(), "runtime room clear resets status service")
	player.free();target.free()

func check_merge_and_invalid() -> void:
	var data: Dictionary = JSON.parse_string(FileAccess.get_file_as_string("res://data/builds/prototype.json"))
	var weaker: Dictionary = data.statuses[0].duplicate(true)
	weaker.id = "weaker_slow"
	weaker.move_scale = 0.8
	data.statuses.append(weaker)
	var manager := Statuses.new()
	manager.configure(BuildLoader.new().decode(data))
	var enemy = actor("brute",Vector3.ZERO)
	manager.apply(enemy,"weaker_slow",1.0,source)
	manager.apply(enemy,"test_slow",1.0,source)
	check(enemy.control_move_scale == builds.status("test_slow").move_scale,"different slows take strongest, never multiply")
	manager.remove(enemy,"test_slow")
	check(enemy.control_move_scale == 0.8,"removing strongest reveals remaining weaker slow")
	manager.clear();enemy.free()
	for field in ["bad_kind","duration","response","extra","version"]:
		var invalid: Dictionary = data.duplicate(true)
		match field:
			"bad_kind": invalid.statuses[0].kind = "burn"
			"duration": invalid.statuses[0].max_duration_sec = 0.01
			"response": invalid.status_rules.default_response_id = "missing"
			"extra": invalid.statuses[0].script = "unimplemented"
			"version": invalid.schema_version = 2
		check(BuildLoader.new().decode(invalid) == null,"invalid status content rejected: " + field)
	var only_split: Dictionary = builds.upgrade("impact_blast").duplicate(true)
	only_split.ranks[0].allowed_origins = ["split_projectile"]
	check(not Caps.eligible(only_split,Caps.summarize_plan(builds,BuildFixture.compile(builds,{},"debug_arrow").actions.debug_arrow)),"derived-only carrier absent before split")
	check(Caps.eligible(only_split,Caps.summarize_plan(builds,BuildFixture.compile(builds,{"split":1},"debug_arrow").actions.debug_arrow)),"derived-only carrier appears after split grant")
