extends "res://tests/action_build_runtime.gd"
const InputAdapter = preload("res://presentation/combat/combat_input.gd")
const CooldownText = preload("res://presentation/combat/skill_cooldown_text.gd")

func run() -> void:
	builds=BuildLoader.new().load_catalog()
	combat=CombatLoader.new().load_catalog()
	resolver.configure(builds)
	var f:=setup([])
	check(f.program.actions.primary.ability_ids.size()==3 and f.program.actions.special.form_id=="sword_heavy" and f.program.actions.skill.form_id=="sword_wave", "zero Build grants all three actions")
	check(not builds.has_upgrade("sword_wave_form") and not builds.has_upgrade("sword_heavy_form"), "obsolete unlock/restore cards removed")
	var legacy:Dictionary=f.program.actions.duplicate(true)
	legacy.erase("skill")
	check(not f.player.set_action_program(legacy,combat), "old two-action wiring explicitly rejected")
	for upgrade in ["contact_freeze","impact_blast","pierce","split"]:
		check(resolver.legal_operations({"selections":[],"revision":0},upgrade).any(func(op):return op.action_id=="skill"), "base skill eligible for " + upgrade)
	for id in ["primary","special","skill"]:
		f.player.runner.tick(10.0)
		cast(f,id)
		check(f.player.runner.action_id==id, "all base actions execute: "+id)
	check(f.runtime.projectiles().size()==1,"only Q produces the base projectile")
	clean(f)
	# Three separate cores and ranks compile without leaking into any other action.
	f=setup([select("impact_blast","primary"),select("contact_freeze","special"),select("impact_blast","skill"),select("pierce","skill")])
	check(f.program.actions.primary.effects.size()==1 and f.program.actions.special.effects.size()==1 and f.program.actions.skill.effects.size()==2,"three-way bindings remain independent")
	var victim=actor("brute",1,Vector3.FORWARD)
	cast(f,"skill");f.runtime.tick(.2)
	check(not victim.control_locked,"Q blast does not inherit heavy freeze")
	clean(f)
	f=setup([select("impact_blast","primary"),select("contact_freeze","skill")])
	victim=actor("brute",1,Vector3.FORWARD)
	cast(f,"special")
	check(victim.health.current<victim.health.maximum and not victim.control_locked and f.runtime.projectiles().is_empty(),"heavy remains useful melee damage without primary/Q effects")
	clean(f)
	# Reversed event orders resolve identically, with only one shared Runner.
	for order in [["primary","special","skill"],["skill","primary","special"],["special","skill","primary"],["primary","skill","special"],["special","primary","skill"],["skill","special","primary"]]:
		f=setup([])
		for id in order:f.player.request_action(id,100)
		f.player.step(.001)
		f.runtime.tick(.001)
		check(f.player.runner.action_id=="skill" and f.player.runner.cast_id==1 and f.runtime.projectiles().size()==1,"same-frame priority independent of OS order")
		check(f.player.runner.cooldown_for("special")==0.0 and f.player.runner.cooldown_for("primary")==0.0,"Q does not spend other action cooldowns")
		clean(f)
	f=setup([])
	f.player.request_action("skill",101);f.player.request_dodge();f.player.step(.001)
	check(f.player.runner.cast_id==0 and f.player.dodge_left>0.0,"dodge wins over Q")
	clean(f)
	f=setup([])
	var camera:=Camera3D.new();root.add_child(camera)
	var blocked:Dictionary={"value":true}
	var input:=InputAdapter.new(f.player,camera,func():return blocked.value)
	var key:=InputEventKey.new();key.physical_keycode=KEY_Q;key.pressed=true
	input.event(key)
	check(f.player.buffered_action_id.is_empty(),"modal/pause gate blocks Q")
	blocked.value=false
	key.echo=true;input.event(key)
	check(f.player.buffered_action_id.is_empty(),"held Q key repeat cannot queue shots")
	key.echo=false;input.event(key);f.player.step(.001);f.runtime.tick(.001)
	check(f.runtime.projectiles().size()==1,"physical Q fires without unlock")
	var field:=LineEdit.new();root.add_child(field);field.grab_focus();await process_frame
	input.event(key)
	check(f.player.buffered_action_id.is_empty(),"text focus blocks Q")
	field.free()
	for locale in ["zh_CN","en"]:
		TranslationServer.add_translation(load("res://generated/locales/%s.po" % locale));TranslationServer.set_locale(locale)
		check(not CooldownText.format_for(f.player).contains("combat.") and CooldownText.format_for(f.player).contains("1.0"),"localized Q countdown uses actual timer")
	var remaining:float=f.player.runner.cooldown_for("skill")
	f.player.step(0.0)
	check(f.player.runner.cooldown_for("skill")==remaining,"zero-time pause does not advance Q cooldown")
	f.player.runner.tick(1.0)
	check(not CooldownText.format_for(f.player).contains("1.0"),"HUD transitions out of cooldown")
	camera.free();clean(f)
	print("THREE_ACTIONS ",JSON.stringify({"failures":failures}))
	quit(0 if failures.is_empty() else 1)
