extends Resource
## Art parameters only. No target selection, damage, status or gameplay RNG.
@export var duration_sec: float
@export var charge_sec: float
@export var target: Vector3
@export var strike_offsets: PackedVector3Array
@export var strike_delays: PackedFloat32Array
@export var strike_heights: PackedFloat32Array
@export var strike_widths: PackedFloat32Array
@export var pulse_times: PackedFloat32Array
@export var pulse_weights: PackedFloat32Array
@export var pulse_decay_sec: float
@export var bolt_duration_sec: float
@export var shape_rate: float
@export var shape_count: int
@export var bolt_segments: int
@export var bolt_jitter: float
@export var bolt_width: float
@export var branch_count: int
@export var branch_span: Vector2
@export var branch_drop: Vector2
@export var branch_width_ratio: float
@export var corona_width_ratio: float
@export var visual_seed: int
@export var core_material: ShaderMaterial
@export var corona_material: ShaderMaterial
@export var sigil_material: ShaderMaterial
@export var ring_material: ShaderMaterial
@export var flash_material: ShaderMaterial
@export var smoke_material: ShaderMaterial
@export var spark_material: Material
@export var debris_material: Material
@export var debris_mesh: Mesh
@export var ground_radius: float
@export var ground_height: float
@export var ground_arc_count: int
@export var ground_arc_segments: int
@export var arc_lifetime_sec: float
@export var ring_lifetime_sec: float
@export var ring_radius: float
@export var flash_size: float
@export var flash_lifetime_sec: float
@export var spark_count: int
@export var spark_size: Vector2
@export var spark_speed: Vector2
@export var spark_lifetime: Vector2
@export var spark_gravity: float
@export var debris_count: int
@export var debris_size: Vector2
@export var debris_speed: Vector2
@export var debris_lifetime: Vector2
@export var debris_gravity: float
@export var debris_bounce: float
@export var debris_drag: float
@export var smoke_count: int
@export var smoke_size: Vector2
@export var smoke_lifetime: Vector2
@export var smoke_spread: float
@export var smoke_rise: float
@export var light_color: Color
@export var light_energy: float
@export var light_radius: float
@export var fade_curve: Curve
